spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    driver-class-name: org.postgresql.Driver
#    username: postgres
#    password: postgres
  profiles:
    include:
      - transactionclassification
  batch:
    job:
      enabled: false